// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject7;

internal sealed partial class Vsix
{
    public const string Id = "VSIXProject7.c94113be-2260-4c66-8f36-ef3993bebd0e";
    public const string Name = "VSIXProject7";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Tim Heuer";
    public const string Tags = "";
}
