// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject7;

using System;

/// <summary>
/// Helper class that exposes all GUIDs used across VS Package.
/// </summary>
internal sealed partial class PackageGuids
{
    public const string VSIXProject7String = "a39debec-50c7-48a2-8a7d-282261a08687";
    public static Guid VSIXProject7 = new Guid(VSIXProject7String);
}
/// <summary>
/// Helper class that encapsulates all CommandIDs uses across VS Package.
/// </summary>
internal sealed partial class PackageIds
{
    public const int MyCommand = 0x0100;
}